CREATE TABLE TBL_ROLE(
	ID			BIGSERIAL PRIMARY KEY,
    STR_ROLE	VARCHAR(40) NOT NULL
);

CREATE TABLE TBL_USUARIO(
	ID				BIGSERIAL PRIMARY KEY,
    STR_EMAIL       VARCHAR(40) NOT NULL UNIQUE,
    STR_SENHA  		VARCHAR(40) NOT NULL,
    STR_TIPO_PROFISSIONAL VARCHAR(15) NOT NULL,
    BOO_ADMIN  		CHAR(1) NOT NULL DEFAULT 'N'
);

CREATE TABLE TBL_DENTISTA(
	ID				BIGSERIAL PRIMARY KEY,
	STR_NOME 	VARCHAR(40),	 
    STR_GENERO       	VARCHAR(20),
    STR_CONSELHO VARCHAR(20),
    STR_REGISTRO VARCHAR(20),
    STR_CODIGO_BRASILEIRO_OCUPACAO VARCHAR(20),
    FK_USUARIO BIGINT REFERENCES TBL_USUARIO(ID) UNIQUE
);

CREATE TABLE TBL_RECEPCIONISTA(
	ID				BIGSERIAL PRIMARY KEY,
	STR_NOME 	VARCHAR(40),	 
    STR_GENERO       	VARCHAR(20),
    FK_USUARIO BIGINT REFERENCES TBL_USUARIO(ID) UNIQUE
);

CREATE TABLE TBL_RECEPCIONISTA_DENTISTA(
	FK_RECEPCIONISTA BIGINT REFERENCES TBL_RECEPCIONISTA(ID),
	FK_DENTISTA BIGINT REFERENCES TBL_DENTISTA(ID)
);

CREATE TABLE TBL_USUARIO_ROLE(
    FK_USUARIO INTEGER REFERENCES TBL_USUARIO (ID),
    FK_ROLE INTEGER REFERENCES TBL_ROLE (ID)
);

CREATE TABLE TBL_CLINICA(
    ID BIGSERIAL PRIMARY KEY,
    STR_NOME VARCHAR(500) NOT NULL,
    NUM_CNPJ BIGINT NOT NULL,
    BOO_ATIVO BOOLEAN NOT NULL DEFAULT(TRUE)
);

CREATE TABLE TBL_USUARIO_CLINICA(
    FK_USUARIO INTEGER REFERENCES TBL_USUARIO (ID),
    FK_CLINICA INTEGER REFERENCES TBL_CLINICA (ID)
);