--ROLES
INSERT INTO TBL_ROLE VALUES(1, 'ADMIN');
INSERT INTO TBL_ROLE VALUES(2, 'COMUN');
INSERT INTO TBL_ROLE VALUES(3, 'SECRETARIA');
INSERT INTO TBL_ROLE VALUES(4, 'PROFISSIONAL');

--USUARIOS
INSERT INTO TBL_USUARIO VALUES(1, 'admin@gmail.com', md5('admin'), MD5('admin@gmail.comadmin'),'RECEPCIONISTA', 'TRUE');

--DENTISTA

--RECEPCIONISTA
INSERT INTO TBL_RECEPCIONISTA(ID, STR_NOME, STR_GENERO, FK_USUARIO) VALUES(1, 'ADMINISTRADOR','FEMININO', 1);

--RECEPCIONISTA_DENTISTA

--USUARIO ROLES
INSERT INTO TBL_USUARIO_ROLE VALUES(1, 1);

--CLINICA
INSERT INTO TBL_CLINICA(ID, STR_NOME, NUM_CNPJ, BOO_ATIVO) VALUES(1, 'Clínica Odontologica Porto Alegre', 31640886000161, TRUE);
INSERT INTO TBL_CLINICA(ID, STR_NOME, NUM_CNPJ, BOO_ATIVO) VALUES(2, 'Clínica Sorriso Fácil', 63878725000105, TRUE);

--CLINICA USUARIO
INSERT INTO TBL_USUARIO_CLINICA(FK_USUARIO, FK_CLINICA) values (1, 1);
INSERT INTO TBL_USUARIO_CLINICA(FK_USUARIO, FK_CLINICA) values (1, 2);

