ALTER SEQUENCE TBL_ROLE_ID_SEQ RESTART WITH 10;
ALTER SEQUENCE TBL_USUARIO_ID_SEQ RESTART WITH 10;
ALTER SEQUENCE TBL_CLINICA_ID_SEQ RESTART WITH 10;
ALTER SEQUENCE TBL_DENTISTA_ID_SEQ RESTART WITH 10;
ALTER SEQUENCE TBL_RECEPCIONISTA_ID_SEQ RESTART WITH 10;