CREATE TABLE TBL_USUARIO_CLINICA(
	ID BIGSERIAL PRIMARY KEY,
	STR_EMAIL VARCHAR(100) NOT NULL UNIQUE,
	STR_HASH_KEY VARCHAR(100) NOT NULL,
	STR_TIPO_PROFISSIONAL VARCHAR(15),
	UNIQUE(STR_EMAIL)
);

CREATE TABLE TBL_AUDITORIA(
	ID BIGSERIAL PRIMARY KEY,
	DTA_ATUALIZACAO TIMESTAMP,
	STR_TIPO_ACAO_AUDITORIA VARCHAR(20),
	STR_TABELA VARCHAR(20),
	NUM_ID_ENTIDADE	INTEGER,
	STR_USUARIO VARCHAR(100) NOT NULL,
	STR_DADOS JSONB NOT NULL
);

CREATE TABLE TBL_CONTATO(
  ID				BIGSERIAL PRIMARY KEY,
  STR_EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_CEP(
	ID				BIGSERIAL PRIMARY KEY,
    STR_CEP       	VARCHAR(10) NOT NULL
);

CREATE TABLE TBL_SIGLA(
  ID				BIGSERIAL PRIMARY KEY,
  STR_SIGLA VARCHAR(2) NOT NULL
);

CREATE TABLE TBL_BAIRRO(
  ID				BIGSERIAL PRIMARY KEY,
  STR_NOME VARCHAR(40) NOT NULL
);


CREATE TABLE TBL_ESTADO(
	ID	BIGSERIAL PRIMARY KEY,
    STR_NOME    VARCHAR(40) NOT NULL,
    FK_SIGLA 	BIGINT REFERENCES TBL_SIGLA (ID)
);

CREATE TABLE TBL_CIDADE(
	ID	BIGSERIAL PRIMARY KEY,
    STR_NOME    VARCHAR(40) NOT NULL,
    FK_ESTADO 	BIGINT REFERENCES TBL_ESTADO (ID)
);

CREATE TABLE TBL_ENDERECO(
	ID	BIGSERIAL PRIMARY KEY,
	STR_ENDERECO    VARCHAR(100) NOT NULL,
	STR_PONTO_REFERENCIA    VARCHAR(100) NULL,
	STR_COMPLEMENTO    VARCHAR(100) NULL,
	NUM_NUMERO 	INTEGER NOT NULL,
	FK_CEP 		BIGINT REFERENCES TBL_CEP (ID),
	FK_CIDADE 	BIGINT REFERENCES TBL_CIDADE (ID),
	FK_BAIRRO	BIGINT REFERENCES TBL_BAIRRO (ID)
);

CREATE TABLE TBL_CONVENIO(
	ID	BIGSERIAL PRIMARY KEY,
	STR_NOME    VARCHAR(40) NOT NULL,
	STR_CNPJ    VARCHAR(30) NULL,
	STR_RAZAO_SOCIAL    VARCHAR(100) NULL,
	FK_ENDERECO 	BIGINT REFERENCES TBL_ENDERECO (ID),
	FK_CONTATO	BIGINT REFERENCES TBL_CONTATO (ID)
);

CREATE TABLE TBL_TIPO_CONSULTA(
	ID	BIGSERIAL PRIMARY KEY,
	STR_NOME    VARCHAR(40) NOT NULL,
	STR_COR_PRIMARIA VARCHAR(10),
	STR_COR_SECUNDARIA VARCHAR(10)
);

CREATE TABLE TBL_STATUS(
	ID	BIGSERIAL PRIMARY KEY,
	STR_NOME    VARCHAR(40) NOT NULL,
	STR_COR VARCHAR(20)
	
);

CREATE TABLE TBL_PACIENTE(
	ID	BIGSERIAL PRIMARY KEY,
	STR_CPF    VARCHAR(30) NOT NULL,
	STR_RG	   VARCHAR(30) NOT NULL,
	STR_NOME   VARCHAR(40) NOT NULL,
	STR_GENERO VARCHAR(20) NOT NULL,
	DTA_DATA_NASCIMENTO TIMESTAMP,
	STR_ESTADO_CIVIL VARCHAR(20) NOT NULL,
	STR_INDICACAO VARCHAR(40),
	STR_PROFISSAO VARCHAR(40),
	FK_CONTATO BIGINT REFERENCES TBL_CONTATO (ID),
	FK_ENDERECO BIGINT REFERENCES TBL_ENDERECO (ID)
);

CREATE TABLE TBL_TELEFONE(
	ID				BIGSERIAL PRIMARY KEY,
    NUM_NUMERO       	INTEGER NOT NULL,
    NUM_DDD INTEGER NOT NULL,
    STR_TIPO_TELEFONE VARCHAR(40),
    FK_CONTATO BIGINT REFERENCES TBL_CONTATO (ID)
);

CREATE TABLE TBL_AGENDA(
	ID				BIGSERIAL PRIMARY KEY,
	FK_USUARIO_CLINICA BIGINT REFERENCES TBL_USUARIO_CLINICA (ID)
);

CREATE TABLE TBL_EVENTO(
	ID				BIGSERIAL PRIMARY KEY,
	BOO_ENCAIXE  BOOLEAN NOT NULL DEFAULT('N'),
	STR_OBSERVACAO VARCHAR(1000) NULL,
	DTA_INICIO TIMESTAMP,
	DTA_FIM TIMESTAMP,
	FK_STATUS BIGINT REFERENCES TBL_STATUS (ID),
	FK_TIPO_CONSULTA BIGINT REFERENCES TBL_TIPO_CONSULTA (ID),
	FK_PACIENTE BIGINT REFERENCES TBL_PACIENTE (ID),
	FK_CONVENIO BIGINT REFERENCES TBL_CONVENIO (ID),
	FK_AGENDA BIGINT REFERENCES TBL_AGENDA (ID)
);

CREATE TABLE TBL_PACIENTE_CONVENIO(
	FK_PACIENTE BIGINT REFERENCES TBL_PACIENTE(ID),
	FK_CONVENIO BIGINT REFERENCES TBL_CONVENIO(ID)
);