--CONTATOS
INSERT INTO TBL_CONTATO(ID, STR_EMAIL) VALUES('1','TESTE@GMAIL.COM.BR');
INSERT INTO TBL_CONTATO(ID, STR_EMAIL) VALUES('2','GENEROSO.FERNANDO@GMAIL.COM.BR');

--CEP
INSERT INTO TBL_CEP(ID, NUM_CEP) VALUES('1',90650040);
INSERT INTO TBL_CEP(ID, NUM_CEP) VALUES('2',88960000);
INSERT INTO TBL_CEP(ID, NUM_CEP) VALUES('3',80880010);

--SIGLA
INSERT INTO TBL_SIGLA(ID, STR_SIGLA) VALUES(1, 'RS');
INSERT INTO TBL_SIGLA(ID, STR_SIGLA) VALUES(2, 'RJ');

--BAIRRO
INSERT INTO TBL_BAIRRO(ID, STR_NOME) VALUES(default, 'ZONA SUL');
INSERT INTO TBL_BAIRRO(ID, STR_NOME) VALUES(default, 'MENINO DEUS');

--ESTADO
INSERT INTO TBL_ESTADO(ID, STR_NOME, FK_SIGLA) VALUES(1, 'RIO GRANDE DO SUL', 1);
INSERT INTO TBL_ESTADO(ID, STR_NOME, FK_SIGLA) VALUES(2, 'RIO DE JANEIRO', 2);

--CIDADE
INSERT INTO TBL_CIDADE(ID, STR_NOME, FK_ESTADO) VALUES(1, 'GRAVATAI', 1);
INSERT INTO TBL_CIDADE(ID, STR_NOME, FK_ESTADO) VALUES(2, 'PORTO ALEGRE', 1);
INSERT INTO TBL_CIDADE(ID, STR_NOME, FK_ESTADO) VALUES(3, 'RIO DE JANEIRO', 2);

--ENDERECO
INSERT INTO TBL_ENDERECO(ID, STR_ENDERECO, STR_PONTO_REFERENCIA, STR_COMPLEMENTO, NUM_NUMERO, FK_CEP, FK_CIDADE, FK_BAIRRO) VALUES(1, 'AV. NEREU RAMOS', 'NENHUM', 'NENHUM', 1300, 2, 1, 1);
INSERT INTO TBL_ENDERECO(ID, STR_ENDERECO, STR_PONTO_REFERENCIA, STR_COMPLEMENTO, NUM_NUMERO, FK_CEP, FK_CIDADE, FK_BAIRRO) VALUES(2, 'AV CENTENÁRIO', 'PRÓXIMO RODOVIÁRIA', 'NENHUM', 225, 3, 2, 1);

--CONVENIO
INSERT INTO TBL_CONVENIO(ID, STR_NOME, STR_CNPJ, STR_RAZAO_SOCIAL, FK_ENDERECO, FK_CONTATO) VALUES(1, 'ITAU', '24.245.515/0001-26', 'ITAU S.A.', 2, 1);

--TIPO CONSULTA
INSERT INTO TBL_TIPO_CONSULTA(ID, STR_NOME) VALUES(1, 'ORÇAMENTO');
INSERT INTO TBL_TIPO_CONSULTA(ID, STR_NOME) VALUES(2, 'LIMPEZA');
INSERT INTO TBL_TIPO_CONSULTA(ID, STR_NOME) VALUES(3, 'AVALIAÇÃO');

--PACIENTE
INSERT INTO TBL_PACIENTE(ID, STR_CPF, STR_RG, STR_NOME, STR_GENERO, DTA_DATA_NASCIMENTO, STR_ESTADO_CIVIL, FK_CONTATO, FK_ENDERECO, FK_CONVENIO) VALUES(1, '029.316.120-81', '3.912.177', 'ANDRÉ CARDOSO NUNES', 'MASCULINO', '1982-05-15', 'SOLTEIRO', 1, 2, 1);

--PROFISSIONAL
INSERT INTO TBL_PROFISSIONAL(ID, STR_NOME, STR_GENERO, STR_CONSELHO, STR_REGISTRO, STR_CODIGO_BRASILEIRO_OCUPACAO) VALUES(1, 'PAULO FERRAZ', 'MASCULINO', 'CRO/SC', '1324', '132');
INSERT INTO TBL_PROFISSIONAL(ID, STR_NOME, STR_GENERO, STR_CONSELHO, STR_REGISTRO, STR_CODIGO_BRASILEIRO_OCUPACAO) VALUES(2, 'MARCIO LONGNE', 'MASCULINO', 'CRO/SC', '2456', '132');

--TELEFONE
INSERT INTO TBL_TELEFONE(ID, NUM_NUMERO, NUM_DDD, STR_TIPO_TELEFONE, FK_CONTATO, FK_PROFISSIONAL) VALUES(1, 35330318, 48, 'RESIDENCIAL', 1,NULL);
INSERT INTO TBL_TELEFONE(ID, NUM_NUMERO, NUM_DDD, STR_TIPO_TELEFONE, FK_CONTATO, FK_PROFISSIONAL) VALUES(2, 99988778, 48, 'CELULAR', NULL, 1);

--AGENDA
INSERT INTO TBL_AGENDA(ID,FK_PROFISSIONAL) VALUES(1, 1);

--EVENTO
INSERT INTO TBL_EVENTO(ID, BOO_CONFIRMADO, BOO_ENCAIXE, STR_STATUS_EVENTO, STR_OBSERVACAO, NUM_ANO, NUM_MES, NUM_DIA, NUM_HORA, NUM_MINUTO, FK_TIPO_CONSULTA, FK_PACIENTE, FK_AGENDA) VALUES(1, TRUE, FALSE, 'ABERTO', 'NENHUM', 2016, 5, 10, 14, 0, 1, 1, 1);